name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: jigar
          POSTGRES_PASSWORD: jigar
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://jigar:jigar@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby 3.1.6 and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6
          bundler-cache: true

      - name: Create the database
        run: bundle exec rails db:create

      - name: Migrate the database
        run: bundle exec rails db:migrate

      - name: Load database schema
        run: bundle exec rails db:schema:load

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby 3.1.6 and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6
          bundler-cache: true